name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'static_website/**' # Only run this workflow if files in the static_website directory change

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Specify your Node.js version
      
      - name: Install dependencies
        run: npm install
        working-directory: ./static_website
      
      - name: Run tests
        run: npm test
        working-directory: ./static_website

  deploy:
    runs-on: ubuntu-latest
    needs: test # This job will only run if the 'test' job is successful

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3 # Action for deploying to GitHub Pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./static_website # Specify the directory containing your static files
