name: CI Workflow

on:
  push:
    branches:
      - main  

jobs:
  terraform:
    name: Terraform Plan and Apply
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws_access_key_id: ${{ secrets.TERRAFORMID }}
        aws_secret_access_key: ${{ secrets.TERRAFORMSECRET }}
        aws_region: us-east-1

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.5.0  

    - name: Terraform Init
      run: terraform init
      working-directory: terraform  

    - name: Terraform Plan
      run: terraform plan
      working-directory: terraform  

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: terraform  

  docker:
    name: Docker Build and Test
    runs-on: ubuntu-latest
    needs: terraform  

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build the Docker image
      run: |
        docker build -t python-s3-upload .
      working-directory: terraform 

    - name: Run the Docker container
      run: |
        docker run --rm python-s3-upload
      working-directory: terraform 
